### ISSUE TITLE
Parrot AR Drone 1.0?

### ISSUE THREAD

**Issue by albertosantini** [felixge/node-ar-drone#11]
Ok, I am lazy and I may try it before wondering.

Is the module compatible with the first release of ar.drone?

If it is not, maybe it would be nice to add a note in the README.

P.S.: I read CONTRIBUTING doc. The note is there. Thanks.

**Comment by drezac** [comment]
Sorry- old thread, but I'm having trouble connecting wirelessly to the AR Drone using this method and wondering what I'm missing. I don't see anything in the code about how to connect to the drone. 

Thoughts?

**Comment by albertosantini** [comment]
You need to connect your box (mac, linux or pc) to the hotspot of the drone.

**Comment by drezac** [comment]
Ah- this is a Parrot Mini Drone rolling spider. I might have that confused with the AR Drone.
