### ISSUE TITLE
Support for ARDroneSDK3 / bebop?

### ISSUE THREAD

**Issue by wiseman** [felixge/node-ar-drone#112]
Has anyone looked at [ARDroneSDK3](https://github.com/ARDroneSDK3), or the possibility of expanding node-ar-drone to support the Bebop drone?

**Comment by daqo** [comment]
Hi Felix, 

I'm working on controlling ArDrone using hand gestures for my master Thesis. I am using Bebop; currently node-ar-drone is not compatible with it. I'm gonna try to fork your repo and try to make it compatible with new API set. Any suggestion or a place to start would be appreciated.

Thanks.

**Comment by wiseman** [comment]
See https://github.com/hybridgroup/node-bebop
