### ISSUE TITLE
Drone WIFI connection - or firmware issue? 

### ISSUE THREAD

**Issue by drezac** [felixge/node-ar-drone#113]
Hey folks- 

I'm looking into trying this method to connect to a Parrot Rolling Spider, but can't see any documentation on how to connect to the drone via the .js file. 

I have a noisy Wifi network, and wonder if that's the problem. Not of my commands are working. 

Thoughts?

**Comment by drezac** [comment]
Ah- this is the Parrot Mini Drone. Not the Parrot.

**Comment by wiseman** [comment]
Right, this library is for the AR.Drone.  For the Rolling Spider you might take a look at this: https://github.com/FluffyJack/node-rolling-spider
