### ISSUE TITLE
Bebop Drone Support

### ISSUE THREAD

**Issue by BKPetkov** [felixge/node-ar-drone#115]
Any suggestions for modifying this library for use with the Parrot Bebop drones? Do any Bebop-compatible repos exist?

**Comment by wiseman** [comment]
See #112 and https://github.com/ARDroneSDK3/ARSDKBuildUtils, but the short answer is that this code is not compatible, but there is an SDK available.

**Comment by wiseman** [comment]
See https://github.com/hybridgroup/node-bebop
