### ISSUE TITLE
Low Level Control

### ISSUE THREAD

**Issue by Daomaster** [felixge/node-ar-drone#125]
I'm just wondering if there any way that I could just send the pitch roll yaw to the drone instead of tell it to go front left and right, since right now I wanted to do a PID control with the drone in order to work with tracking system later. If anyone could send me an example that would really helpful. Thanks

**Comment by wiseman** [comment]
You might want to take a look at page 36 of the [AR.Drone Developer Guide](http://www.msh-tools.com/ardrone/ARDrone_Developer_Guide.pdf), where it describes the `PCMD` and `PCMD_MAG` commands; As far as I know those are the only commands that let's you control the pitch/roll/yaw, and that's what the node-ar-drone `Client.front`, `Client.back`, etc. commands actually use.
