### ISSUE TITLE
Indoor and outdoor flight

### ISSUE THREAD

**Issue by Birdy45** [felixge/node-ar-drone#126]
The parrot drone has different settings for outdoor and indoor flight. This seems to affect its PID system for sustaining stable flight. I have tried to find a way to set the drone to either indoor or outdoor flight using this library, but cannot find how to do this. Is there a way of doing this using ar-drone?

**Comment by wiseman** [comment]
I think `client.config('control:outdoor', true)` will tell the drone it's flying outdoors.

From page 79 of the [AR.Drone Developer Guide](http://www.msh-tools.com/ardrone/ARDrone_Developer_Guide.pdf):

## CONTROL:outdoor
*Description*:  This settings tells the control loop that the AR.Drone is flying outside.

Setting the indoor/outdoor flight will load the corresponding indoor/outdoor_control_yaw, indoor/outdoor_euler_angle_max and indoor/outdoor_control_vz_max.

_Note_: This settings enables the wind estimator of the AR.Drone 2.0 , and thus should always be enabled when flying outside. _Note_: This settings corresponds to the Outdoor flight setting of AR.FreeFlight.

AT command example : `AT*CONFIG=605,"control:outdoor","TRUE"`
