### ISSUE TITLE
Drone takes off unstably

### ISSUE THREAD

**Issue by nateheath** [felixge/node-ar-drone#129]
I just started using this library with my ar drone 1.0 and whenever I type takeoff() in the terminal the drone would take off but it would go everywhere and it wouldn't have a stabilized hover which I find really weird, what could be the problem ?

**Comment by wiseman** [comment]
Before taking off, try doing a "flat trim" by running `ftrim()` and see if that makes a difference.

**Comment by nateheath** [comment]
Oh I fixed this already , got it to work properly, all you had to do was reset the drone and it flies like normal again lol to anyone that has this problem

**Comment by nateheath** [comment]
Thanks tho wiseman

**Comment by wiseman** [comment]
Glad to hear you figured it out!
