### ISSUE TITLE
Supported drones 2016

### ISSUE THREAD

**Issue by clankill3r** [felixge/node-ar-drone#133]
I was wondering which drones are supported besides the Parrot AR drone 2.0?
Please list here if you know a drone with support.

And if the parrot bebop 2 for example is not supported. Then how can be checked if it is possible to program support for it?

**Comment by felixge** [comment]
AR Drone 2 and 1 are supported

**Comment by tanmayb123** [comment]
Quick Question - Is any edition of the AR Drone 2 supported? I can get access to an AR Drone Power Edition tomorrow (http://www.bestbuy.ca/en-CA/product/parrot-parrot-ar-drone-2-0-power-edition-quadcopter-drone-with-camera-ready-to-fly-red-pf721005bi/10273736.aspx?lang=en-CA&pcname=&sku=10273736&path=3153be675a3f25aecb458530d5f0d034en02), but not an Elite Edition. Would that work? Just wanted to make sure before going ahead and buying it...

Thanks!

**Comment by felixge** [comment]
There is no technical difference between the editions. The only thing different is color and included batteries.

**Comment by tanmayb123** [comment]
Alright - Thank you very much!
