### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by JakubTrj** [felixge/node-ar-drone#134]
Hello!

First of all, I'd like to thanks Felix for his remarkable work! I really appreciate and have a lot of fun flying my ar-drone.

Therefore several issues appeared during my drone testing, here there are:
1. Is it possible to control yaw changes while drone is hovering in same place? I successfully managed to turn drone around using oriented roundel, when i was turning the roundel, drone is respectively turning in the same direction, but i'd like to turn it autonomously by using some of your commands or commands in SDK. (I tried to use Eschnou ardrone-autonomy scripts, but they cause many control and stabilization troubles so i decided use only node-ar-drone).
2. Is it possible to control 2 or more ar-drones from one computer? 
3. I use these commands:
client.config('video:video_channel', 3);
client.config('general:navdata_demo', 'TRUE');
client.config('general:navdata_options', 105971713); //from SDK
client.config('detect:detect_type', 12); // detecting oriendel black-white roundel on the ground
client.config('detect:detections_select_h', 0); //turning off frontal camera detection
client.config('detect:detections_select_v', 3); //tag_type oriented roundel
client.config('control:flying_mode', 1<<1);

to set hovering on oriented roundel. After taking off it successfully manage to detect first roundel, fly to it's position and hover above, but when i try to fly 2m forward to next roundel and set hovering above, drone seems not to see the second roundel (it's not flying directly above roundel position). In my script I change flying_mode from 1<<1 to 0 and fly forward, after dron stops, i change it back to 1<<1. Is that correct? How to improve script to make drone behave as i would like to?

Regards, 
Jakub

**Comment by wiseman** [comment]
1. Yes. Use `client.clockwise` and `client.counterClockwise`.

2. Yes. Instead of connecting to the drone's wireless network, you have to get each drone to connect to an existing network. See https://github.com/daraosn/ardrone-wpa2. You will need to determine what the IP address of each drone is, and create client objects connected to those addresses.

3. You might just try setting the drone's forward speed instead of using hovering mode.
