### ISSUE TITLE
how to access accelerometer data?

### ISSUE THREAD

**Issue by koalapenguins** [felixge/node-ar-drone#139]
Hi! I'm new here, so i'll do my best to ask clearly

Is there a function to access the accelerometer readings/data of the AR.Drone?

i have a feeling it's in the navdata part of this library, but i can't exactly find the function specifically for accelerometers

**Comment by wiseman** [comment]
You can get the attitude of the drone, is that sufficient? It's in `navdata.demo.rotation`.  For example, this code (from https://github.com/wiseman/ardrone-browser-3d) computes a rotation matrix from the Euler angles in `navdata.demo.rotation`:

```
Drone.prototype.updateState = function(navdata) {
  var euler = navdata.demo.rotation;
  var m = new THREE.Matrix4();
  // I couldn't find documentation on the AR.Drone Euler angle order,
  // but this seems to work.
  m.makeRotationFromEuler(new THREE.Vector3(euler.roll * PI180,
                                            euler.yaw * -PI180,
                                            euler.pitch * PI180),
                          'YZX');
  this.matrix = m;
  this.matrixAutoUpdate = false;
  this.updateMatrixWorld(true);
};
```
