### ISSUE TITLE
External sensors

### ISSUE THREAD

**Issue by cipek** [felixge/node-ar-drone#163]
Is it possible to connect external sensors to the drone and read data from it via node-ar-drone? I believe that would require some modifications to the library itself, but is the drone able to transmit data from the sensor to the node.js server?

**Comment by wiseman** [comment]
Yes. See http://lemondronor.com/blog/indexphp/2013/4/cheap-ads-b-on-amateur-drones and https://github.com/wiseman/webflight-traffic for an example of reading a USB-based sensor on the drone.
