### ISSUE TITLE
Support for config acks and multiconfig options (for the cool stuff)

### ISSUE THREAD

**Issue by bkw** [felixge/node-ar-drone#33]
I wrote a gist on why we need to do something about client.config() and what my current plan of attack is here: https://gist.github.com/4416785

Maybe this should go into the new api? It's really time I had a look at it.

**Comment by wiseman** [comment]
Looks like maybe ROS has a complete config implementation: https://github.com/AutonomyLab/ardrone_autonomy/pull/26

**Comment by liuruitv** [comment]
亲爱的朋友，感谢您对我们的支持！如果需要，我们的工作人员会在尽快联系您。

另外，我要告诉您的是，我决定免费与您分享一些我不为人知的营销与管理秘诀。这些秘诀帮助我的客户在市场取得了巨大的成功。我有一个单纯而美好的愿望，希望更多的人能了解和应用这些秘诀，创造更多的财富。

请点击下面的链接，进入下载页面，马上下载：http://liuruitv.com/
