### ISSUE TITLE
Accessing the bottom camera on the drone

### ISSUE THREAD

**Issue by ajayjain** [felixge/node-ar-drone#35]
I want to access the image data from the bottom camera and I was hoping that accessing it would be similar to the front camera (eg PngStream).

I started by looking at PaVEParser.js, particularly at data stored in _frame.

Can anyone provide some guidance or help on this? Thanks.

**Comment by sayadyaghoobi** [comment]
i'm working with python modules. when i want to switch between cameras, it does'nt show right images sometimes. i've tried to use bottom camera using this code:
drone.setConfig("video:video_channel","1")
but sometimes it give me the front camera
if anyone solved this problem please let me know. thanks
