### ISSUE TITLE
animate commands don't work.

### ISSUE THREAD

**Issue by nickponline** [felixge/node-ar-drone#42]
Hi there, 

The drone seems to be ignoring all animate commands like flips.For example:

var arDrone = require('ar-drone');
var client = arDrone.createClient();

client.takeoff();

client
  .after(3000, function() {
    this.animate('flipLeft', 15);
  })
  .after(1000, function() {
    this.stop();
    this.land();
  });

Just takes off and then lands. Is there a reason for this?

**Comment by patriciocordova** [comment]
@nickponline what is the config parameter? did you solve it?

**Comment by nickponline** [comment]
I don't think I got it working.

**Comment by patriciocordova** [comment]
ok! please, leave the issue opened then
