### ISSUE TITLE
How to capture directly to USB: video_on_usb not working?

### ISSUE THREAD

**Issue by nischelwitzer** [felixge/node-ar-drone#65]
Hi,

I would like to use node-ar-drone and capture at the same
time the video directly on a USB-Pen on the AR Drone 2.0.
It works fine if i control the Drone with the iOS/Android App.

In the SDK2.0 PDF (page 87) i found the config: video:video_on_usb
and tried: client.config('video:video_on_usb', true);
but still no video will be captured when i use node/node-ar-drone.

What could be the problem?

Thanks,
                Alex

**Comment by cschell** [comment]
Has this issue been resolved in the meantime? Or is there another way to simply dump all recordings on an usb-pen?
