### ISSUE TITLE
Support for uploading ephemeris

### ISSUE THREAD

**Issue by wiseman** [felixge/node-ar-drone#74]
As far as I know the Flight Recorder GPS requires ephemeris to be uploaded from the app.  It would be nice to be able to do this and get a faster fix without having to use the app.

I see the Free Flight app send the following GPS-related commands, but I don't know yet how it's actually uploading the ephemeris:

```
AT*CONFIG=1355,"gps:longitude","-118.277018"
AT*CONFIG=1366,"gps:altitude","115.649048"
AT*CONFIG=1378,"gps:accuracy","65.000000"
AT*CONFIG=1386,"gps:ephemeris_uploaded","RESET"
AT*CONFIG=1468,"gps:ephemeris_uploaded","f437ec69aa76c90f4fe8d64b3122016a"
```

**Comment by dlenski** [comment]
Apologies for the random tangent here but I thought this might be interesting to other users of products based on CSR GPS. I came across this thread while searching for more information on the Sirf Instant Fix ephemeris file format. This format is also used by the TomTom GPS watches (as in [ryanbinns/ttwatch](//github.com/ryanbinns/ttwatch) and [dlenski/ttblue](//github.com/dlenski/ttblue)).

It's really useful to find the link @wiseman posted to the 14-day ephemeris file: http://download.parrot.com/ephemerides/packedDifference.f2p14enc.ee

That file appears to be completely functionally equivalent to the 3-day ephemeris file provided by TomTom (except that the parrot.com version gives a longer timespan of ephemeris data :+1:): http://gpsquickfix.services.tomtom.com/fitness/sifgps.f2p3enc.ee

By the way, if any of you want to use the Russian [GLONASS](//en.wikipedia.org/wiki/GLONASS) satellites, which are supposed to be more accurate at high latitudes, then you might try using the 3-day GLONASS ephemeris file provided by TomTom: http://gpsquickfix.services.tomtom.com/fitness/sifglo.f2p3enc.ee

**Comment by wiseman** [comment]
Cool, thanks for the info, @dlenski.
