### ISSUE TITLE
Activate GPS navdata

### ISSUE THREAD

**Issue by wiseman** [felixge/node-ar-drone#75]
Even with the Flight Recorder GPS accessory, from a cold boot the AR.Drone doesn't send GPS data as part of navdata.

The following command will cause the drone to begin including GPS data (this is what the iOS app sends):

```
client.config('general:navdata_options', 777060865);
// 777060865 = 101110010100010000001000000001
// The default options value is
//     65537 = 000000000000010000000000000001
```

**Comment by lwsang13** [comment]
Hi @wiseman !!
I have Big problem! Please help me...
I'm using ARdrone1.0...I attatched gps to my ardrone. And i tested it using Arduino and linux....
but I don't know how to get data using Visual studio(c++).
Do you know how to get data from Ardrone 1.0??
And can you expain ZIMMU_3000 ?? is it similar with gps?
