### ISSUE TITLE
Problem with demo.altitude

### ISSUE THREAD

**Issue by ghost** [felixge/node-ar-drone#91]
Hello: 
I am new with the node-ar-node and I am trying to use the altitude section within the navdata to read what the current height of the drone is (I move the drone by hand). But I don't get anything back. What is wrong?

```
var arDrone = require('ar-drone')
  ,  arDroneConstants = require('ar-drone/lib/constants')
  ;

function navdata_option_mask(c){
    return 1 << c;
}
var navdata_options = (
    navdata_option_mask(arDroneConstants.options.DEMO)

);

var drone1 = new arDrone.createClient();
drone1.config('general:navdata_demo', false);
drone1.config('general:navdata_options', navdata_options);

drone1.on('navdata', function (d) {

        console.log(d.demo.altitude);

});
```

And returns : 

```
TypeError: Cannot read property 'altitude' of undefined
```

Have I to change something in `/lib/navdata/parseNavdata.js` ?

Thank you

**Comment by albertJ32** [comment]
Great thread! solved a problem i was having for a while
